changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 'Features'
      labels:
        - feature
        - feat
    - title: 'Bug Fixes'
      labels:
        - fix
        - bug
    - title: 'Maintenance'
      labels:
        - chore
        - refactor
        - test
