services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./config/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - confide-central

  central:
    image: ghcr.io/confide-gg/confide/central:${CENTRAL_VERSION:-latest}
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://confide:${POSTGRES_PASSWORD}@postgres:5432/confide_central
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - RUST_LOG=${RUST_LOG:-info,confide_central=info}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - CALLS_RELAY_BIND_HOST=0.0.0.0
      - CALLS_RELAY_BIND_PORT=10000
      - CALLS_RELAY_PUBLIC_HOST=${DOMAIN}
      - DB_MAX_CONNECTIONS=${DB_MAX_CONNECTIONS:-100}
      - DB_API_POOL_SIZE=${DB_API_POOL_SIZE:-30}
      - DB_WEBSOCKET_POOL_SIZE=${DB_WEBSOCKET_POOL_SIZE:-100}
      - WEBSOCKET_MESSAGE_BUFFER_SIZE=${WEBSOCKET_MESSAGE_BUFFER_SIZE:-256}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - CALLS_RELAY_TOKEN_SECRET=${CALLS_RELAY_TOKEN_SECRET}
    ports:
      - "10000:10000/udp"
    depends_on:
      - postgres
      - redis
    networks:
      - confide-central

  postgres:
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: confide
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: confide_central
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=${POSTGRES_MAX_CONNECTIONS:-200}"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "effective_cache_size=1536MB"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=2621kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
    networks:
      - confide-central
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U confide -d confide_central"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    command:
      - "redis-server"
      - "--requirepass"
      - "${REDIS_PASSWORD}"
      - "--maxmemory"
      - "${REDIS_MAX_MEMORY:-512mb}"
      - "--maxmemory-policy"
      - "allkeys-lru"
      - "--appendonly"
      - "yes"
      - "--appendfsync"
      - "everysec"
      - "--save"
      - "900 1"
      - "--save"
      - "300 10"
      - "--save"
      - "60 10000"
      - "--tcp-backlog"
      - "511"
      - "--timeout"
      - "300"
      - "--tcp-keepalive"
      - "60"
      - "--maxclients"
      - "10000"
    volumes:
      - redis_data:/data
    networks:
      - confide-central
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:

networks:
  confide-central:
    driver: bridge
